### ISSUE TITLE
Error logging in (Maybe?)

### ISSUE THREAD

**Issue by ToxicRT** [D34DPlayer/Monochrome#1]
Hi, I'm installing Monochrome and everything was fine but logging in doesn't work, I don't know what I've done wrong, but is there a solution?

I'm from the scan: Knight No Scanlation (Spanish) :p

![image](https://user-images.githubusercontent.com/43280922/131571317-c9449dae-97f0-4dff-a981-092a7782e29f.png)

**Comment by D34DPlayer** [comment]
The issue should have been fixed, if it didn't work try creating a new admin user with `make create_admin`

**Comment by ToxicRT** [comment]
Yes, it is solved, thank you very much, but now I have another error in the upload attempt. 
I tried to fix it on my own but failed. (sorry to bother you again) 

![image](https://user-images.githubusercontent.com/43280922/131585496-b72857f8-2172-4d66-b876-c836542566b8.png)
![image](https://user-images.githubusercontent.com/43280922/131585535-ae6cc9c8-dfc6-44b7-8b18-35c3fdc78f20.png)
![image](https://user-images.githubusercontent.com/43280922/131585603-e4e617e4-c2ab-41e4-b64a-a0408cf6d132.png)

**Comment by D34DPlayer** [comment]
Fixed (1.0.2), however the 422 error shouldn't give a not authenticated error, weird. Also, please make new issues if you encounter more of them so I can keep track of them more easily.
