### ISSUE TITLE
Problems with images that are 720 or smaller in width.

### ISSUE THREAD

**Issue by ToxicRT** [D34DPlayer/Monochrome#3]
Well I managed to upload a chapter and it works well with the manga but for the manhwas (webtoon) with a width of 720 (or less) it looks too weird compared to a manga, and with none of the vertical reading modes or webtoon it is seen well.

You can confirm it with this manga (which looks good):
https://reader.knightnoscanlation.com/manga/95bbbe8b-8c52-4c82-ae4c-34428be2c572

and also this webtoon which is the one that looks weird:
https://reader.knightnoscanlation.com/chapters/c83ce36f-1d99-4640-b474-4bf9572fdb46

**Comment by ToxicRT** [comment]
I also have an extra question, can I add custom html code for ads or similar things in the future?

**Comment by D34DPlayer** [comment]
This should have been fixed with #8 and #10
Now the chapters can be marked as webtoons when uploaded/edited. This will enable the webtoon reader for those.
Please give it a try and tell me how it went.

**Comment by D34DPlayer** [comment]
About the suggestion, I'm not totally against it but it isn't a priority, as it would need quite some thought to do it properly without it breaking the app's overall appearance.

For now you can add HTML in the About page

**Comment by ToxicRT** [comment]
I made the change and it works fine but I see small spaces between the images, otherwise I do not see any problem.

**Comment by D34DPlayer** [comment]
Do you use the vertical reader or did you edit the chapter for it to be a webtoon, and have the webtoon reader?

This is how I see an image change with the webtoon reader, no small space between:
![image](https://user-images.githubusercontent.com/58138378/132105490-f5e433cd-ad39-4886-a19d-f76eb658ee24.png)

**Comment by ToxicRT** [comment]
How strange I see spaces between the images with the webtoon mode 

![image](https://user-images.githubusercontent.com/43280922/132105835-839ec45c-8ec3-4f07-8f45-194e664f77b5.png)

**Comment by D34DPlayer** [comment]
Weird, I'm looking to your chapter in your app and it looks fine to me, both on Chromium and Firefox, maybe you can open it in incognito mode, or inspect the element to see where it comes from.

**Comment by ToxicRT** [comment]
padding-bottom, I modified it and now it is perfect 

![image](https://user-images.githubusercontent.com/43280922/132106209-1c4b11ba-dc37-484b-b3a0-e576f1844ddb.png)
